version: "3.8"
services:
  expo-app:
    build: .
    ports:
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - ./:/opt/my-app:delegated
      - /opt/my-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
