version: "3.8"
services:
  backend:
    build: ./backend/dz_delivery
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=dz_delivery
      - DB_USER=myuser
      - DB_PASSWORD=password
      - DB_HOST=db
    volumes:
      - ./backend/dz_delivery:/app # Mount code to container
    depends_on:
      - db

  frontend:
    build: ./frontend/dz_delivery
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/dz_delivery:/app # Mount code to container
      #- /app/node_modules # Mount the container's node modules as a seperate
    profiles:
      - frontend
      - full

  mobile:
    build: ./mobile/dz_delivery
    ports:
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PYTHONUNBUFFERED=1
      - REACT_NATIVE_PACKAGER_HOSTNAME=10.5.3.243 # Change this to your local machine's IP address
    volumes:
      - ./mobile/dz_delivery/:/opt/my-app:delegated
      - /opt/my-app/node_modules
    stdin_open: true
    tty: true
    profiles:
      - mobile
      - full

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dz_delivery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
