version: "3.8"
services:
  backend:
    build: ./backend/dz_delivery
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=dz_delivery
      - DB_USER=myuser
      - DB_PASSWORD=password
      - DB_HOST=db
    volumes:
      - ./backend/dz_delivery:/app # Mount code to container
    depends_on:
      - db

  frontend:
    build: ./frontend/dz_delivery
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/dz_delivery:/app # Mount code to container
      - /app/node_modules # Mount the container's node modules as a seperate module

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dz_delivery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
