# Generated by Django 5.1.3 on 2024-12-26 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer_feedback',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer_rating',
        ),
        migrations.AddField(
            model_name='delivery',
            name='dropoff_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Dropoff Location'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Pickup Location'),
        ),
        migrations.AddField(
            model_name='package',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='package',
            name='current_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Current Address'),
        ),
        migrations.AddField(
            model_name='package',
            name='customer_feedback',
            field=models.TextField(blank=True, verbose_name='Customer Feedback'),
        ),
        migrations.AddField(
            model_name='package',
            name='customer_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Customer Rating'),
        ),
    ]
