# Generated by Django 5.1.3 on 2024-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Pickup'),
        ),
    ]
