# Generated by Django 5.1.3 on 2024-12-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_delivery_estimated_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='additional_fees',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object containing fee type and amount', verbose_name='Additional Fees'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_address',
            field=models.JSONField(blank=True, default={'alg': 3}, verbose_name='Dropoff Location'),
            preserve_default=False,
        ),
    ]
