# Generated by Django 5.1.3 on 2024-12-31 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_delivery_additional_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dropoff_window_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dropoff Window End'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dropoff_window_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dropoff Window Start'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_delivery_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Estimated Delivery Duration'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_window_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup Window End'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_window_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup Window Start'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='distance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='driver_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Driver Rating'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Dropoff Location'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount'),
        ),
    ]
