# Generated by Django 5.1.3 on 2024-12-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_delivery_dropoff_window_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Street Address')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit/Apt')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('building_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Building Type')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='deliverystatus',
            name='location',
        ),
        migrations.RemoveField(
            model_name='package',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pickup_address',
        ),
    ]
