# Generated by Django 5.1.3 on 2024-12-31 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_address_remove_delivery_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dropoff_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_deliveries', to='delivery.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_deliveries', to='delivery.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_updates', to='delivery.address'),
        ),
        migrations.AddField(
            model_name='package',
            name='current_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_packages', to='delivery.address'),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_packages', to='delivery.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='pickup_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_packages', to='delivery.address'),
            preserve_default=False,
        ),
    ]
