# Generated by Django 5.1.3 on 2024-12-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_documenttype_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['-is_required']},
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='order',
        ),
    ]
