# Generated by Django 5.1.3 on 2024-12-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['-is_driver_required', '-is_client_required', 'name']},
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='is_courier_required',
            new_name='is_driver_required',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_courier_verified',
            new_name='is_driver_verified',
        ),
    ]
